### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ak-seyam** [abdo1819/simple_arm#3]
if we are planning to make it a SPA i suggest using a SPA framework to do this job, i'm not pointing to react cuz i don't how to reach the terminal from node.js yet, i would prefer something python based I've found some stuff tackling SPA w/ flask am gonna read them later or if you know something betterrrrrrr....

**Comment by abdo1819** [comment]
https://github.com/abdo1819/simple_arm/pull/2#issuecomment-560017438

i was to create it with no framework for those reasons if you have good option we may use it

**Comment by abdo1819** [comment]
we are using react
